### ISSUE TITLE
help with build_inputs?

### ISSUE THREAD

**Issue by sid-kap** [badi/pip2nix#3]
Hi! I'm pretty excited to use nix-pip to nix-ify my python dependencies, but I'm running into problems with building my dependencies.

I'm running `nix-pip` in a directory, where my `.nix-pip.rc` file is:

```yaml
# -*- mode: yaml -*-

nixpkgs: import <nixpkgs> {}

python: pkgs.python35
pythonPackages: pkgs.python35Packages

requirements:
  packages:
    - scrapy

setup_requires: {}

build_inputs:
  cffi:
    - libffi
  lxml:
    - libxslt
    - libxml2
```

For some reason, when it's building the dependencies of scrapy (cffi and lxml) the required libraries aren't found. Here's the output I got from nix-pip: https://pastebin.com/PyW53ApA

Does anyone know what I'm doing wrong?

Some of the relevant lines from the nix-pip output:
```
(lines 158-160)
  *********************************************************************************                      
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?                      
  *********************************************************************************    
(line 203)
  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory          
(lines 280-284)
    Building lxml version 3.8.0.                                                                        
    Building without Cython.                                                                            
    ERROR: /bin/sh: xslt-config: command not found                                                      
                                                                                                         
    ** make sure the development packages of libxml2 and libxslt are installed **  
```
